namespace AiGroupChat.Application.DTOs.AiService;

/// <summary>
/// Response from the Python AI service.
/// This is an internal DTO used for service-to-service communication.
/// </summary>
public class AiGenerateResponse
{
    /// <summary>
    /// The AI's generated response text.
    /// </summary>
    /// <example>React is a great choice for this project because...</example>
    public string Response { get; set; } = string.Empty;

    /// <summary>
    /// Metadata about the generation (tokens, latency, model used).
    /// </summary>
    public AiResponseMetadataDto Metadata { get; set; } = new();

    /// <summary>
    /// Optional attachment (image, code file, etc.) generated by the AI.
    /// </summary>
    public AiAttachment? Attachment { get; set; }
}

/// <summary>
/// Metadata about the AI generation for tracking and cost calculation.
/// </summary>
public class AiResponseMetadataDto
{
    /// <summary>
    /// Provider that handled the request.
    /// </summary>
    /// <example>gemini</example>
    public string Provider { get; set; } = string.Empty;

    /// <summary>
    /// Specific model used for generation.
    /// </summary>
    /// <example>gemini-1.5-pro</example>
    public string Model { get; set; } = string.Empty;

    /// <summary>
    /// Number of input tokens (context + query).
    /// </summary>
    /// <example>450</example>
    public int TokensInput { get; set; }

    /// <summary>
    /// Number of output tokens (AI response).
    /// </summary>
    /// <example>280</example>
    public int TokensOutput { get; set; }

    /// <summary>
    /// Response latency in milliseconds.
    /// </summary>
    /// <example>2340</example>
    public int LatencyMs { get; set; }
}

/// <summary>
/// Attachment generated by the AI (image, code file, etc.).
/// </summary>
public class AiAttachment
{
    /// <summary>
    /// Attachment type. Values: "image", "code", "document".
    /// </summary>
    /// <example>image</example>
    public string Type { get; set; } = string.Empty;

    /// <summary>
    /// Suggested filename for the attachment.
    /// </summary>
    /// <example>architecture-diagram.png</example>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Base64-encoded file content.
    /// </summary>
    /// <example>iVBORw0KGgo...</example>
    public string Base64 { get; set; } = string.Empty;
}